name: flutter_stack
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  freezed_annotation: ^3.0.0
  openapi_generator_annotations: ^6.1.0
  one_of: ">=1.5.0 <2.0.0"
  one_of_serializer: ">=1.5.0 <2.0.0"
  built_value: ">=8.4.0 <9.0.0"
  built_collection: ">=5.1.1 <6.0.0"
  dio: ^5.8.0
  provider: ^6.1.1
  api_client:
    path: api/api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^3.0.0
  openapi_generator: ^6.1.0
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
